apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-exp
  namespace: argocd
  argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://github.com/iuliiaryzhova/nifi-registry-deploy
    targetRevision: main
    path: helm/postgresql-exp

  destination:
    server: https://kubernetes.default.svc
    namespace: nifi-registry-exp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
