apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      initContainers:
        - name: download-jdbc
          image: curlimages/curl:8.6.0
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              set -e
              mkdir -p /opt/nifi-drivers
              curl -fL "{{ .Values.jdbc.driverUrl }}" -o /opt/nifi-drivers/postgresql.jar
              chmod 0644 /opt/nifi-drivers/postgresql.jar
          volumeMounts:
            - name: drivers
              mountPath: /opt/nifi-drivers

      containers:
        - name: nifi-registry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
              protocol: TCP

          envFrom:
            - secretRef:
                name: {{ .Values.postgres.secretName }}

          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms512m -Xmx1024m"

            - name: NIFI_REGISTRY_DB_URL
              value: "jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/$(POSTGRES_DB)"
            - name: NIFI_REGISTRY_DB_CLASS
              value: "{{ .Values.jdbc.driverClass }}"
            - name: NIFI_REGISTRY_DB_DIR
              value: "/opt/nifi-drivers"

            - name: NIFI_REGISTRY_FLOW_PROVIDER
              value: "database"

            - name: NIFI_REGISTRY_DB_USER
              value: "$(POSTGRES_USER)"
            - name: NIFI_REGISTRY_DB_PASS
              value: "$(POSTGRES_PASSWORD)"

          volumeMounts:
            - name: drivers
              mountPath: /opt/nifi-drivers

      volumes:
        - name: drivers
          emptyDir: {}
