image:
  repository: apache/nifi-registry
  tag: "2.6.0"
  pullPolicy: IfNotPresent

service:
  port: 18080

postgres:
  host: postgresql
  port: 5432
  secretName: postgres-secret

jdbc:
  driverUrl: https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.9/postgresql-42.7.9.jar
  driverClass: org.postgresql.Driver
